# Generated by Django 5.2.5 on 2025-08-22 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_subscriptionplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='subscriptionPlan',
        ),
    ]
