# Generated by Django 5.2.5 on 2025-09-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_activitylogs_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylogs',
            name='action_type',
            field=models.CharField(choices=[('invoice_created', 'Invoice Created'), ('employee_created', 'Employee Created'), ('bill_created', 'Bill Created'), ('branch_created', 'Branch Created'), ('stock_transfer_initiated', 'Stock Transfer Initiated'), ('cash_recon_created', 'Cash Recon Created'), ('invoice_created', 'Invoice Created'), ('inventory_item_created', 'Inventory Item Created'), ('product_created', 'Product Created'), ('payment_received', 'Payment Received'), ('customer_added', 'Customer Added'), ('user_added', 'User Added'), ('inventory_alert', 'Inventory Alert'), ('tax_filed', 'Tax Filed'), ('payroll_processed', 'Payroll Processed')], max_length=100),
        ),
    ]
