# Generated by Django 5.1.2 on 2025-08-24 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branche_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tenant',
        ),
    ]
