# Generated by Django 5.2.5 on 2025-08-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('dairy', 'Dairy'), ('meat', 'Meat'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('grains', 'Grains'), ('nuts', 'Nuts'), ('spices', 'Spices'), ('pasta', 'Pasta'), ('canned_goods', 'Canned Goods'), ('baking_supplies', 'Baking Supplies'), ('snacks', 'Snacks'), ('pet_food', 'Pet Food'), ('household_items', 'Household Items'), ('beverages', 'Beverages'), ('personal_care', 'Personal Care'), ('baby_care', 'Baby Care'), ('pet_care', 'Pet Care'), ('office_supplies', 'Office Supplies'), ('arts_and_crafts', 'Arts and Crafts'), ('books_and_media', 'Books and Media'), ('sports_equipment', 'Sports Equipment'), ('musical_instruments', 'Musical Instruments'), ('outdoor_equipment', 'Outdoor Equipment'), ('tools', 'Tools'), ('furniture', 'Furniture'), ('home_decor', 'Home Decor'), ('garden_supplies', 'Garden Supplies'), ('garage_and_storage', 'Garage and Storage'), ('auto_parts', 'Auto Parts'), ('vintage_and_collectibles', 'Vintage and Collectibles'), ('other', 'Other')], max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_stock', models.PositiveIntegerField(default=0)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('minimum_stock_level', models.PositiveIntegerField(default=0)),
                ('vat_applicable', models.BooleanField(default=False)),
                ('is_perishable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
