# Generated by Django 5.2.5 on 2025-09-11 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_order_options_order_cashier_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 11, 5, 13, 33, 567539, tzinfo=datetime.timezone.utc)),
        ),
    ]
