# Generated by Django 5.2.5 on 2025-09-11 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_order_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 11, 5, 30, 5, 833609, tzinfo=datetime.timezone.utc)),
        ),
    ]
