# Generated by Django 5.2.5 on 2025-09-12 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_order_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 12, 17, 47, 49, 468572, tzinfo=datetime.timezone.utc)),
        ),
    ]
