# Generated by Django 5.2.5 on 2025-09-13 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_order_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 13, 2, 30, 33, 355444, tzinfo=datetime.timezone.utc)),
        ),
    ]
