# Generated by Django 5.2.5 on 2025-09-15 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_location', '0002_initial'),
        ('products', '0009_alter_order_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='multi_location.branch'),
        ),
    ]
