# Generated by Django 5.1.2 on 2025-08-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdrawer',
            name='current_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cashdrawer',
            name='opening_balance',
            field=models.IntegerField(),
        ),
    ]
