# Generated by Django 5.1.2 on 2025-08-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptier',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
