# Generated by Django 5.2.5 on 2025-09-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='membership_tier',
            field=models.CharField(choices=[('regular', 'Regular'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='MembershipTier',
        ),
    ]
