# Generated by Django 5.1.2 on 2025-08-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_membershiptier_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
