# Generated by Django 5.1.2 on 2025-08-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_location', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='tenants',
            new_name='tenant',
        ),
    ]
