# Generated by Django 5.2.5 on 2025-08-30 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('return_type', models.CharField(choices=[('paye_return', 'PAYE Return'), ('corporation_tax', 'Corporation Tax'), ('withholding_tax', 'Withholding Tax'), ('capital_gains_tax', 'Capital Gains Tax'), ('rental_income_tax', 'Rental Income Tax'), ('vat_return', 'VAT Return'), ('excise_duty_return', 'Excise Duty Return'), ('customs_duties_return', 'Customs Duties Return')], max_length=50)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filed', 'Filed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TaxLiability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('tax_type', models.CharField(choices=[('vat', 'Value Added Tax (VAT)'), ('paye', 'Pay As You Earn (PAYE)'), ('withholding_tax', 'Withholding Tax'), ('corporation_tax', 'Corporation Tax'), ('excise_duty', 'Excise Duty'), ('income_tax', 'Income Tax')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'tax liabilities',
                'unique_together': {('period', 'tax_type', 'tenant')},
            },
        ),
    ]
