# Generated by Django 5.2.5 on 2025-08-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('min_stock', models.PositiveIntegerField(default=0)),
                ('max_stock', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('categories', models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Accessories', 'Accessories'), ('Furniture', 'Furniture'), ('Apparel', 'Apparel'), ('Books', 'Books'), ('Home & Garden', 'Home & Garden'), ('Toys & Games', 'Toys & Games'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Health & Beauty', 'Health & Beauty'), ('Automotive', 'Automotive')], max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_status', models.CharField(choices=[('In Stock', 'In Stock'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], max_length=100, null=True)),
            ],
        ),
    ]
