# Generated by Django 5.1.2 on 2025-08-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_stock_status_alter_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Accessories', 'Accessories'), ('Furniture', 'Furniture'), ('Apparel', 'Apparel'), ('Books', 'Books'), ('Home & Garden', 'Home & Garden'), ('Toys & Games', 'Toys & Games'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Health & Beauty', 'Health & Beauty'), ('Automotive', 'Automotive')], max_length=100, null=True),
        ),
    ]
