# Generated by Django 5.1.2 on 2025-08-29 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_categories'),
        ('multi_location', '0003_rename_tenants_branch_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multi_location.branch'),
        ),
    ]
