# Generated by Django 5.2.5 on 2025-09-10 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_order'),
        ('tenants', '0003_alter_activitylogs_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount received from the customer', max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_reference', models.CharField(blank=True, max_length=50)),
                ('card_last4', models.CharField(blank=True, help_text='Last 4 digits of the card for record keeping.', max_length=4)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='products.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Payments',
                'ordering': ['-timestamp'],
            },
        ),
    ]
