# Generated by Django 5.2.5 on 2025-09-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('tenants', '0005_alter_activitylogs_action_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employees',
        ),
    ]
