# Generated by Django 5.2.5 on 2025-09-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_rename_employee_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
