# Generated by Django 5.2.5 on 2025-09-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_employees_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='allowances',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Allowance',
        ),
    ]
