# Generated by Django 5.2.5 on 2025-08-21 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='products.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(choices=[('dairy', 'Dairy'), ('meat', 'Meat'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('grains', 'Grains'), ('nuts', 'Nuts'), ('spices', 'Spices'), ('pasta', 'Pasta'), ('canned_goods', 'Canned Goods'), ('baking_supplies', 'Baking Supplies'), ('snacks', 'Snacks'), ('pet_food', 'Pet Food'), ('household_items', 'Household Items'), ('beverages', 'Beverages'), ('personal_care', 'Personal Care'), ('baby_care', 'Baby Care'), ('pet_care', 'Pet Care'), ('office_supplies', 'Office Supplies'), ('arts_and_crafts', 'Arts and Crafts'), ('books_and_media', 'Books and Media'), ('sports_equipment', 'Sports Equipment'), ('musical_instruments', 'Musical Instruments'), ('outdoor_equipment', 'Outdoor Equipment'), ('tools', 'Tools'), ('furniture', 'Furniture'), ('home_decor', 'Home Decor'), ('garden_supplies', 'Garden Supplies'), ('garage_and_storage', 'Garage and Storage'), ('auto_parts', 'Auto Parts'), ('vintage_and_collectibles', 'Vintage and Collectibles'), ('other', 'Other')], max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('payment_terms', models.CharField(max_length=100)),
                ('credit_limit', models.PositiveBigIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier'),
        ),
    ]
