# Generated by Django 5.2.5 on 2025-08-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='tenant',
        ),
    ]
