# Generated by Django 5.2.5 on 2025-08-23 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_remove_supplier_tenant'),
        ('tenants', '0003_remove_tenant_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('dairy', 'Dairy'), ('meat', 'Meat'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('grains', 'Grains'), ('nuts', 'Nuts'), ('spices', 'Spices'), ('pasta', 'Pasta'), ('canned_goods', 'Canned Goods'), ('baking_supplies', 'Baking Supplies'), ('snacks', 'Snacks'), ('pet_food', 'Pet Food'), ('household_items', 'Household Items'), ('beverages', 'Beverages'), ('personal_care', 'Personal Care'), ('baby_care', 'Baby Care'), ('pet_care', 'Pet Care'), ('office_supplies', 'Office Supplies'), ('arts_and_crafts', 'Arts and Crafts'), ('books_and_media', 'Books and Media'), ('sports_equipment', 'Sports Equipment'), ('musical_instruments', 'Musical Instruments'), ('outdoor_equipment', 'Outdoor Equipment'), ('tools', 'Tools'), ('furniture', 'Furniture'), ('home_decor', 'Home Decor'), ('garden_supplies', 'Garden Supplies'), ('garage_and_storage', 'Garage and Storage'), ('auto_parts', 'Auto Parts'), ('vintage_and_collectibles', 'Vintage and Collectibles'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
