# Generated by Django 5.1.2 on 2025-08-26 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_gstin',
        ),
    ]
