# Generated by Django 5.1.2 on 2025-08-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_customer_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
